### ISSUE TITLE
move xcms adduct list

### ISSUE THREAD

**Issue by stanstrup** [stanstrup/PeakABro#4]
move load.camera.rules and adduct lists to https://github.com/stanstrup/common_mz.
To avoid loading the heavy chemhelper.
Also option to not warn about conflicts.

**Comment by jorainer** [comment]
That would make much sense.
Also I would suggest to store the data not as *xlsx* files, but plain txt files.
Performance could also be improved if you read the file content once (e.g. during package loading) and not each time you call `load.camera.rules`. See e.g. https://github.com/jotsetung/xcmsExtensions/blob/master/R/zzz.R#L19:L21

**Comment by stanstrup** [comment]
Yeah I know xlsx is evil but it is just much easier to understand the file when it is colored by group when you have to expand it...

**Comment by jorainer** [comment]
you can also leave it as xlsx, no prob with that - I guess import works now on all platforms. But reading it once on package startup will have a positive effect on performance.

**Comment by stanstrup** [comment]
There is at least the readxl package now that doesn't have the heavy dependencies of the xlsx package.
